CREATE TABLE STUDENT(ID INT , NAME VARCHAR(50))

--TABLE FOR UPDATE LOG FROM STUDENT TBLE
CREATE TABLE STUDENTLOG (ID INT , ModifiedDate DATETIME)

--TABLE FOR INSERT LOG FROM STUDENT TBLE
CREATE TABLE INSERTLOG (ID INT , ModifiedDate DATETIME)

--TABLE FRO DELETE LOG
CREATE TABLE DELETELOG (ID INT , ModifiedDate DATETIME)

--TRIGGER FOR UPDATE
CREATE TRIGGER STUDENTRECORDS ON STUDENT
FOR UPDATE 
NOT FOR REPLICATION 
AS
 
BEGIN
  INSERT INTO STUDENTLOG
  SELECT ID
    ,getdate()
  FROM inserted
END

--TRIGGER FOR INSERT

CREATE TRIGGER STUDENTINSERT ON STUDENT
FOR INSERT 
NOT FOR REPLICATION 
AS
 
BEGIN
  INSERT INTO INSERTLOG
  SELECT ID
    ,getdate()
  FROM inserted
END
--TRIGGER DELETE

CREATE TRIGGER STUDENTDELETE ON STUDENT
FOR DELETE 
NOT FOR REPLICATION 
AS
 
BEGIN
  INSERT INTO DELETELOG
  SELECT ID
    ,getdate()
  FROM deleted
END

--INSERT INTO STUDENT

INSERT INTO STUDENT(ID,NAME)VALUES(12,'SHUBHAM')
INSERT INTO STUDENT(ID,NAME)VALUES(122,'SHUBHAM')
INSERT INTO STUDENT(ID,NAME)VALUES(12562,'AKASH')

--UPDATE STUDENT
UPDATE STUDENT
SET NAME='HER0'
WHERE ID=12

--DELETE RECORD
DELETE FROM STUDENT WHERE ID=122

--RESULT
SELECT * FROM STUDENTLOG

SELECT * FROM INSERTLOG

SELECT * FROM DELETELOG


--INDEX NON CLUSTERING

CREATE INDEX EXAMPLE
ON EmployeeInfo(FirstName);

SELECT * FROM EXAMPLE